config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tweets#index"
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :tweet, presence: true, length: { in: 6..100 }
    belongs_to :user
    # validates :user, presence: true, length: { in: 6..20 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # before_action :real_user, only: [:edit, :update, :destroy]

  # GET /tweets or /tweets.json
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    # @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    # @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def real_user
  #   @tweet = User.tweets.find_by(id: params[:id])
  #   redirect_to tweets_path, notice: "Not authorised!" if @tweet.nil?
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Twitter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "templates/navbar" %>
    <% if notice %>
     <%= render "layouts/alerts" %>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/templates/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'twitter' ,root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">NewTweet</a>
          </li>        
          <li class="nav-item">
            <%= link_to 'Edit' ,edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out' , destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to 'sign up' ,new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'sign in' ,new_user_session_path, class: "nav-link" %> 
          </li> 
        <% end %>

    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<div class="create-form" style= "width: 100vw;display: flex;flex-direction: column;align-items: center;
  justify-content: center">
    <%= form_with(model: tweet, local: true, html: {class: "tweet-form"}) do |form| %>
      <% if tweet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

          <ul>
            <% tweet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# <div class="input-group mb-2 mr-sm-2 " style="width: 16vw;">
        <div class="input-group-prepend">
          <div class="input-group-text">@</div>
        </div>
        <%= form.text_field :user,class: "form-control", id: "inlineFormInputGroupUsername2",
         placeholder: "Username" %>
      <%# </div> %>

      <div class="field"  style="width: 27vw;">
        <%= form.text_field :tweet,class: "form-control mb-2 mr-sm-2", id: "inlineFormInputName2",
         placeholder: "What's your Tweet today" %>
      </div>
      <div class="field"  style="width: 27vw;">
        <%= form.number_field :user_id, class: "form-control mb-2 mr-sm-2", id: "tweet_user_id",
         value: current_user.id, type: :hidden %>
      </div>
      <%# <%= current_user.name %>
      <div class="actions">
        <%= form.submit "post" ,class: "btn btn-primary my-1" %>
      </div>
    <% end %>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<%= render 'form', tweet: @tweet %>
<!-- <%= link_to 'New Tweet', new_tweet_path %> -->
  <% @tweets.reverse_each do |tweet| %>
   <div class="jumbotron" style="background-color: #e3f2fd;">
      <h2 class="display-16"  style = "font-size: large;"><%= tweet.user.email %></h2>
      <h1 class="display-16"><%= tweet.tweet %></h1>
      <button type="button" class="btn btn-primary"><%= link_to 'Show', tweet,
         style: "color:white;text-decoration:none" %></button>
      <% if tweet.user == current_user %>   
         <button type="button" class="btn btn-primary"><a><%= link_to 'Edit', edit_tweet_path(tweet),
            style: "color:white;text-decoration:none" %></a></button>
         <button type="button" class="btn btn-primary"><a><%= link_to 'Destroy', tweet, method: :delete,
            data: { confirm: 'Are you sure?' }, style: "color:white;text-decoration:none" %></a></button>
      <% end %>
      <hr class="my-4">
   </div>
  <% end %>

<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<p>
  <strong>User:</strong>
  <%= current_user.email %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>